name: my workflow                     # Workflow 이름
on: [push]                            # Event 감지

jobs:                                 # Job 설정
  build:                              # Job ID
    name: hello github action         # Job 이름
    runs-on: ubuntu-18.04             # Job 가상환경 인스턴스
    steps:                            # Steps
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install

      - name: Build                   # React Build
        run: npm run build
